# Default values for landing.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# If provided, these will be used by the deployment
# nodeSelector: XXXXXXX

image:
  repository: docker.io/srcd/code-annotation
  # tag must be received as a parameter
  pullPolicy: IfNotPresent
deployment:
    internalDatabasePath: "/var/code-annotation"
    # gaTrackingID must be received as a parameter
authorization:
    restrictAccessGroup: "org:src-d"
    restrictRequesterGroup: ""
service:
  type: NodePort
  codeAnnotation:
    externalPort: 8080
    internalPort: 8080
    name: code-annotation
ingress:
  kcmClass: default
  annotations:
    kubernetes.io/ingress.class: gce
  tls: true
  # below values are required
  # hostname: "code-annotation.srcd.run"
  # globalStaticIpName: "code-annotation-ip"

# Provide with 'helm install', and do NOT change it when doing 'helm upgrade'
#   github_client:
#   github_secret:
#   jwt_signing_key:
# It's also possible to use deployed secrets by using argument:
# secretName: "existing name"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi
  #
